name: Deploy to ECR

on: push
env:
  AWS_ACCOUNT: 061051224299
  AWS_REGION: eu-west-1
  ECR_REGISTRY: 061051224299.dkr.ecr.eu-west-1.amazonaws.com
  ECR_REPOSITORY: go-app

jobs:
  build:
    name: CI
    runs-on: self-hosted
    steps:
      - name: Set globals
        id: globals
        shell: bash
        run: |
          echo "  ECS_CONTAINER_NAME=go-app" >> "${GITHUB_OUTPUT}"
          echo "  ECS_SERVICE_NAME=surepay-service" >> "${GITHUB_OUTPUT}"
          echo "  ECS_CLUSTER_NAME=surepay-ecs" >> "${GITHUB_OUTPUT}"

      - name: Check out code
        uses: actions/checkout@v4

      - name: Build and tag image
        id: build-image
        env:
          TAG_COMMIT: ${{ github.sha }}
        run: |
          cd app/
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$TAG_COMMIT . 
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$TAG_COMMIT" >> $GITHUB_OUTPUT

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ steps.build-image.outputs.image }}
          format: 'table'
          hide-progress: true
          # exit-code: '1' #Error in case of vulnerabilities
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH' #Ignore low severity vulnerabilities 
          cache: 'false'

      - name: Login to ECR
        id: login-ecr
        env:
          AWS_ACCOUNT: 061051224299
          AWS_REGION: eu-west-1
        run: |
            docker login -u AWS -p $(aws ecr get-login-password --region $AWS_REGION) $ECR_REGISTRY

      - name: Push image
        id: push-image
        env:
          TAG_COMMIT: ${{ github.sha }}
        run: |
          docker push ${{ steps.build-image.outputs.image }}
          sudo rm /root/.docker/config.json

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition surepay-task --query taskDefinition > task-definition.json
          cat task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ steps.globals.outputs.ECS_CONTAINER_NAME }}
          image: ${{ steps.build-image.outputs.image }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ steps.globals.outputs.ECS_SERVICE_NAME }}
          cluster: ${{ steps.globals.outputs.ECS_CLUSTER_NAME }}
          desired-count: 4
          wait-for-service-stability: true