# name: do-the-job
# on: push
# jobs:
#   do-the-job:
#     name: Do the job on the runner
#     runs-on: self-hosted
#     steps:
#       - uses: actions/checkout@v2
#       - name: Hello World
#         run: |
#           echo 'Hello World!'
#           sleep 15
#           echo 'Goodbye!'
name: Deploy to ECR

on: push
env:
  AWS_REGION: eu-west-1
  AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
jobs:
  build:
    name: CI
    runs-on: self-hosted
    steps:

  # Checkout and test app code
    - name: Check out code
      uses: actions/checkout@v2
      with: 
        repository: 'dilsilva/go-load-generator'

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'
    - name: Install dependencies
      run: go get ./cmd/loadgen/ && ls -la
    - name: Unit Test 
      run: go test -v -cover ./... 
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2


    - name: Login to Amazon ECR
      id: login-ecr
      run: |
        # Get the ECR login password and use it to log in to the ECR registry
        result=$(aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com)
        
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
        ECR_REPOSITORY: go-app
        TAG_COMMIT: ${{ github.sha }} 
      run: |

        # Build the Docker image using the specified tags
        sudo docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$TAG_COMMIT .

        # Push the Docker image to the ECR repository using Docker config from the workspace
        sudo docker push $ECR_REGISTRY/$ECR_REPOSITORY:$TAG_COMMIT

        # Remove the Docker config file after pushing the image
        sudo rm -fr ${GITHUB_WORKSPACE}/${GITHUB_RUN_ID}/config.json

        $ECR_REGISTRY/$ECR_REPOSITORY:$TAG_COMMIT >> $GITHUB_OUTPUT


    #Insert vulnerability scan after build
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.28.0
      with:
        image-ref: ${{ steps.login-ecr.outputs.registry }}
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'


    # #Insert Sign Image verification step before deployment
    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition my-task-definition-family --query taskDefinition > task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: my-container
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: my-service
        cluster: my-cluster
        wait-for-service-stability: true
####
